name: challenges
description: A sample command-line to automate 100DaysOfCode challenge tasks
version: 0.0.2
homepage: https://github.com/mukund-kri/challenge
author: Mukund K <mukund.kri@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  path: ^1.4.1
  shell: ^1.0.1
  intl: ^0.15.7
  yaml: any

dev_dependencies:
  test: ^1.0.0

executables:
  challenges:

publish_to: none

